### ISSUE TITLE
Mac Installer Issue

### ISSUE THREAD

**Issue by nbk16** [ambisonictoolkit/atk-reaper#66] opened 2017-03-11 01:07 UTC
I am trying to install the AKT for Reaper 1.0b10 for Mac but it did failed.
Installation start fine but failed at installing into place.
I will love to use it for a project. Any suggestion to make it work?
thanks

**Comment by joslloand** [comment] 2017-03-14 18:57
What version of MacOS are you running?

@lossius do you have any advice?

**Comment by lossius** [comment] 2017-03-15 07:55
Hi @nbk16 , are you able to provide further detail regarding how it failed?

* What version of Mac OS are you at?
* What error message(s) do you see?
* What are your settings for System Preferences > Security & Privacy > General > Allow apps downloaded from

Can you please try changing the latter to "Anywhere" and re-run the installer, and see if that helps? The installer is not code-signed with Apple.

**Comment by nbk16** [comment] 2017-03-15 14:17
Thanks for the reply

I mac 27 Late 2013-Mac OS Yosemite 10.10
3.5 Ghz intel core 3 -16 GB 1600 mhz DDR3
System preference set for Allow apps download from anywhere
using Reaper V 5.35/64 (still in eval time)
 Double click the mpkg it open fine with installer start the install fine but at summary it show message The Installation Failed 
installer encountered an error that caused the installation to fail. contact software manufacter for assistance. 
If you need some file logs or more info let me know.

**Comment by lossius** [comment] 2017-03-27 08:48
I'm not sure what's causing this. I'm on El Capitan myself, so I'm unable to test the installer with Yosemite here, unfortunately. If you have log files, that would be useful.

Alternatively you can download the Windows installer instead. This is a zipped folder with manual instructions for how to manually install the required files, and they can be installed the same way on Mac.

**Comment by nbk16** [comment] 2017-03-27 23:57
hi Lossius
I was finally able to install by using the laptop (same as the imac Yosemite) It did install and i copy the folder ATK and transfert back to the i mac . The only difference was that  i did not have reaper on it. I did reinstall reaper on the imac as a remote and put the ATK folder on the FX folder seems fine they show as JS plug in. 
Right now i'm running with another issue that look like ISSUE # 67 and i am not window. The decoder binaural js plug in is not outputing audio no signal on meter  (the one  i really need) input ok picture ok.
The FOA encoder Diff same issue but Near field fine. I try with wigware ambix binaural and it worked fine.I am using your video to set up reaper thank so much for that for that. 
I did try the spacial workstation 360 it went fine .For the log could guide me on the one you want
I notice also that if itry to open the project from the file i save it do not log the plug in in the session but If i open the application and open the project all akt plug in are there.

**Comment by lossius** [comment] 2018-11-02 21:05
Hi @cdbzb I suggest you download the Windows installer and follow the install inastructions for that instead. That works just as well on Mac, the Mac installer is just ment to make ti a bit easier, but it might sound like it's not managing to do so any longer...

**Comment by joslloand** [comment] 2018-11-02 23:49
As reported by @lossius the issue (https://github.com/ambisonictoolkit/atk-reaper/issues/71) you're experiencing has to do with the with a failure to find the required kernal files (FIR filters) for the plugins which need them.

You could try to manually install these.

See: https://github.com/ambisonictoolkit/atk-kernels

**Comment by lossius** [comment] 2021-11-04 09:02
Closing this issue.

**Closed by lossius** 2021-11-04 09:02 UTC

**Comment by joslloand** [comment] 2021-11-04 18:09
@lossius, I'm presuming this issue resolved by the new installer?:

Version 1.0 beta 11
Released 2021-11-04

**Comment by lossius** [comment] 2021-11-04 19:10
Hi,

I have tested the new installer on two separate macs, one running Big Sur and one running Monterey, and it works well om both.

Some of the above reported issues might have to do with security settings, as we do not code sign the installer. But even this seem to work better with the new installer. There are also some reports that seem to be caused by kernels not being properly installed.  If following the instructions for the manual installer, these problems should be solved.

**Comment by joslloand** [comment] 2021-11-04 19:20
Great! Good to know!
