### ISSUE TITLE
BToAmbix not working

### ISSUE THREAD

**Issue by rellimneb** [ambisonictoolkit/atk-reaper#88] opened 2021-12-15 12:29 UTC
no sound comes through.  I think it can't find  files "acn-sn3d.mosl.txt" and "acn-n3d.mosl.txt"

**Comment by joslloand** [comment] 2021-12-20 21:33
What operating system are you on?
What version of Reaper?
Are you using the latest atk-reaper?

**Comment by rellimneb** [comment] 2021-12-21 09:54
Osx catalina
Reaper 6.42
Latest version of ATK from the installer from the website

**Comment by joslloand** [comment] 2022-01-24 19:14
@lossius, perhaps the installer isn't including the matrix files?

**Comment by lossius** [comment] 2022-01-24 19:31
@rellimneb : This seems to be an install problem. Please download the Windows installer and follow the instructions there    (It works on macOS as well )  This should solve it for you.

I'll close this issue.

**Comment by lossius** [comment] 2022-02-21 21:24
Reopening this issue, as I am able to duplicate with the MacOSX installer. I suspect that the matrixes used for AmbixToB and BtoAmbiX are not properly making it into the installers.

**Comment by lossius** [comment] 2022-02-21 21:54
This issue is caused by the following commit in atk-matrices:

**Comment by lossius** [comment] 2022-02-21 21:55
This issue is caused by the following commit in atk-matrices:

https://github.com/ambisonictoolkit/atk-matrices/commit/ec88956633f2bf02fa5981ba843c4be91ebd0b9d

@joslloand : What files have replaced these ones?

**Comment by lossius** [comment] 2022-02-22 08:43
This issue is a duplicate of #92 I'll close this and further address it as #92 instead, as that issue has some additional information for further debugging.

**Closed as completed by lossius** 2022-02-22 08:43 UTC
Labels: bug
