### ISSUE TITLE
mMatrixDSP.matrix_read_from_file doesn't seem to read from file in linux

### ISSUE THREAD

**Issue by muziker** [ambisonictoolkit/atk-reaper#92] opened 2022-02-14 03:24 UTC
I was trying out AmbiXtoB, and the mMatrixDSP.cell it was reading was empty. The strcpy was pointing to files that were in "ATK/matrices/FOA/encoders/acn-*" but these files are in "ATK/matrices/FOA/encoders/hoa1". 

Because the files appear in both the encoders and decoders directories, and the header section in the files doesn't say " X format encodes into Y format" or "Y format decodes into X format", it's difficult to decide which of these is a valid transformation matrix to read.

**Comment by joslloand** [comment] 2022-02-14 20:02
> Because the files appear in both the encoders and decoders directories, and the header section in the files doesn't say " X format encodes into Y format" or "Y format decodes into X format", it's difficult to decide which of these is a valid transformation matrix to read.

In the ATK's naming convention:
-  _encoding_ means convert _some format_ to _FOA_
- _decoding_ means convert _FOA_ to _some format_

Here's a review of the [naming conventions](https://depts.washington.edu/dxscdoc/Help/Tutorials/ABCs-of-the-ATK.html#Ambisonic%20formats) used by the ATK. (This is for the SuperCollider version.)

Both the encoding and decoding folder should have corresponding "format exchange" matrices.

It looks like there may be a referencing issue here.

@lossius, can you offer further insights / comments?

**Comment by lossius** [comment] 2022-02-22 08:47
#88, reported by @rellimneb is a duplicate of this issue. As mentioned there, this issue probably occurred as a consequence of the following commit in atk-matrices:

https://github.com/ambisonictoolkit/atk-matrices/commit/ec88956633f2bf02fa5981ba843c4be91ebd0b9d

This commit removed the matrices that the AmbiXtoB and BtoAmbiX plugins look for. As they have stayed behind in my own personal ~/librry/Application Support/ATK folder I never discovered the issue myself.

@joslloand : What files have replaced these ones? (I will also take the time now to compare files myself)

**Comment by lossius** [comment] 2022-02-22 11:31
In the process of addressing this, I discovered an issue with reading text files if a comment line contains a comma. We either need to ensure that we have no commas in `*.mosl.txt` files, and/or this needs to be addressed in Reaper.

**Comment by joslloand** [comment] 2022-02-22 20:58
> #88, reported by @rellimneb is a duplicate of this issue. As mentioned there, this issue probably occurred as a consequence of the following commit in atk-matrices:
> 
> [ambisonictoolkit/atk-matrices@ec88956](https://github.com/ambisonictoolkit/atk-matrices/commit/ec88956633f2bf02fa5981ba843c4be91ebd0b9d)
> 
> This commit removed the matrices that the AmbiXtoB and BtoAmbiX plugins look for. As they have stayed behind in my own personal ~/librry/Application Support/ATK folder I never discovered the issue myself.
> 
> @joslloand : What files have replaced these ones? (I will also take the time now to compare files myself)

Ok, having had a look, [Remove redundant hoa1 matrices](https://github.com/ambisonictoolkit/atk-matrices/commit/ec88956633f2bf02fa5981ba843c4be91ebd0b9d) was made within the context of development towards the HOA version of atk-sc3.

What we're seeing is a framework divergence problem, the divergence between atk-sc3's format of HOA as

- acn-n3d (ref radius = 1.5m)

and atk-reaper's (evolving) format of HOA as

- acn-sn3d (re radius = inf), aka _ambix_.

At the moment atk-matrices contains one folder:

- [FOA](https://github.com/ambisonictoolkit/atk-matrices/tree/master/FOA)

One possible solution could be to include a folder labelled **ambix1**, and rename and place the removed matrix files there. (Updating any other required header info.) At this moment I'm _not_ sure what the implications on the atk-sc3 side would be. Parsing issues could be introduced, so we'd need to check for that.

UPDATE: needs closer inspection. These are/were FOA encoders/decoders, so were in the correct place. The issue for atk-sc3 to is use on the fly coefficient generation rather than loading.

@mtmccrea, any thoughts?

**Comment by joslloand** [comment] 2022-02-22 21:00
> @joslloand : What files have replaced these ones? (I will also take the time now to compare files myself)

Forgot to answer... atk-sc3 generates the required coefficients on the fly now. That's why these files were removed, to remove conflict with the atk-sc3 coefficient synthesis.

UPDATE: the matrices were moved to a new location.. atk-sc3 uses these in their new locations. More details below..

**Comment by joslloand** [comment] 2022-02-24 01:05
@lossius, to fix this issue we just need to update where atk-reaper looks for the various hoa1 files.

These are found:

- https://github.com/ambisonictoolkit/atk-matrices/tree/master/FOA/decoders/hoa1
- https://github.com/ambisonictoolkit/atk-matrices/tree/master/FOA/encoders/hoa1

The files weren't removed, they were just moved. (This didn't happen all in one commit, for some reason.)

They had been located one directory higher, so it should be easy to fix...

**Comment by joslloand** [comment] 2022-02-24 20:11
> @lossius, to fix this issue we just need to update where atk-reaper looks for the various hoa1 files.

For instance, [these lines](https://github.com/ambisonictoolkit/atk-reaper/blob/master/plugins/FOA/Decode/BtoAmbiX#L61-L70):

```
/**********************************************************
Updated slider value:
**********************************************************/
@slider

(slider1 == 0) ? (
  strcpy(mFilePath, "ATK/matrices/FOA/decoders/acn-sn3d1.mosl.txt");
) : (
  strcpy(mFilePath, "ATK/matrices/FOA/decoders/acn-n3d1.mosl.txt");
);
```

Will need to be updated to:

```
/**********************************************************
Updated slider value:
**********************************************************/
@slider

(slider1 == 0) ? (
  strcpy(mFilePath, "ATK/matrices/FOA/decoders/hoa1/acn-sn3d1.mosl.txt");
) : (
  strcpy(mFilePath, "ATK/matrices/FOA/decoders/hoa1/acn-n3d1.mosl.txt");
);
```

And [these lines](https://github.com/ambisonictoolkit/atk-reaper/blob/master/plugins/FOA/Encode/AmbiXtoB#L61-L70):

```
/**********************************************************
Updated slider value:
**********************************************************/
@slider

(slider1 == 0) ? (
  strcpy(mFilePath, "ATK/matrices/FOA/encoders/acn-sn3d1.mosl.txt");
) : (
  strcpy(mFilePath, "ATK/matrices/FOA/encoders/acn-n3d1.mosl.txt");
);
```

To:

```
/**********************************************************
Updated slider value:
**********************************************************/
@slider

(slider1 == 0) ? (
  strcpy(mFilePath, "ATK/matrices/FOA/encoders/hoa1/acn-sn3d1.mosl.txt");
) : (
  strcpy(mFilePath, "ATK/matrices/FOA/encoders/hoa1/acn-n3d1.mosl.txt");
);
```

I'll make a new branch, make the changes. @lossius, you can have a look to confirm this resolves everything given the updated matrices (Version 1.0.1).

**Comment by joslloand** [comment] 2022-02-24 20:31
@lossius, here's the relevant commit: c88ccbb9ff6de2b33f7971320bf9a5c872f6351a

You'll want to be on atk-matrices v1.0.1

EDIT: or, can use [atk-matrices v1.0.3](https://github.com/ambisonictoolkit/atk-matrices/releases/tag/v1.0.3) (This is just a github action release update. The actual matrices are the same.) Thanks @dyfer

**Comment by dyfer** [comment] 2022-02-25 22:26
To summarize: as discussed with @joslloand a moment ago, this problem is two-prong:
- the matrices need to be on version >=1.0.1 to address issue with comment symbol in the text files (the issue was not present in older versions of Reaper supposedly)
- paths need to be updated in the JSFX code because of updates pointed out by @joslloand 
`FOA/encoders/acn-n3d1.mosl.txt` -> `FOA/encoders/hoa1/acn-n3d.mosl.txt`
`FOA/encoders/acn-sn3d1.mosl.txt` -> `FOA/encoders/hoa1/acn-sn3d.mosl.txt`
`FOA/decoders/acn-n3d1.mosl.txt` -> `FOA/decoders/hoa1/acn-n3d.mosl.txt`
`FOA/decoders/acn-sn3d1.mosl.txt` -> `FOA/decoders/hoa1/acn-sn3d.mosl.txt`
 (note that the new filename does not include `1`, i.e. `...n3d1.mosl.txt` -> `...n3d.mosl.txt`)

Also, I don't think this issue is linux-specific (might consider updating the topic - unless I'm missing something) - I've observed it on macOS myself

EDIT: to clarify - I've tested the path changes locally and with the new kernels I was able to hear ambix en/decoders again.

**Comment by joslloand** [comment] 2022-02-26 00:07
@lossius, should I do the merge? Or would you like to test first??

EDIT: .zip files ready!! (use [v1.0.3](https://github.com/ambisonictoolkit/atk-matrices/releases/tag/v1.0.3))

**Comment by lossius** [comment] 2022-03-04 12:29
I have updated atk-matrices submodule to 1.0.3. Works locally here, and will be part of the next version. What remains now is to update what atk-matrices files are included in the Win and macOS installers

**Comment by lossius** [comment] 2022-03-04 12:41
Installer scrips etc. are updated to work with atk-matrices v.1.0.3. Closing this issue.

**Closed as completed by lossius** 2022-03-04 12:41 UTC

**Comment by joslloand** [comment] 2022-03-04 19:12
Thanks @lossius !!
