### ISSUE TITLE
Update GUIs for FOA Transforms

### ISSUE THREAD

**Issue by joslloand** [ambisonictoolkit/atk-reaper#24] opened 2016-06-02 23:20 UTC
Update the indication of perceived localization focus from _|rV|_ to _|rE|_.

Mapping to _|rE|_ offers a stronger sense of how localized an encoded planewave will appear after transform.

This change will require an update to the figures presented in documentation for [atk-sc3](https://github.com/ambisonictoolkit/atk-sc3).

To implement will require a brief conversation with @lossius as to details.

**Comment by joslloand** [comment] 2016-06-02 23:24
See also: [Update soundfield transform figures to illustrate rE #11](https://github.com/ambisonictoolkit/atk-sc3/issues/11)

**Comment by joslloand** [comment] 2016-07-18 18:32
Hi @lossius more discussion....

This commit shows how the plots have changed: https://github.com/ambisonictoolkit/atk-sc3/commit/4f6d2fc5d52a07f85e7a34728700a9492ef8d346

From the new Intro-to-the-ATK SCHelp:

> Three useful features are displayed in these plots, providing important insight as to how an input soundfield will be modified by a transform:
> 
> - incidence[4] : illustrated as polar angle
> - quality[5] : illustrated as radius
> - gain[6] : illustrated via colour
> 
> 
> Individual planewaves are coloured with respect to the gain scale at the far left of the figures. Additionally, Front, Left, Back-Left and Back are annotated with a numerical figure for gain, in dB.
> 
> **Soundfield quality**
> 
> The meaning of transformation to soundfield incidence and gain should be clear. Understanding the meaning of soundfield quality takes a little more effort. This feature describes how apparently localised an element in some direction will appear.
> 
> A planewave has a quality measure of 1.0, and is heard as localised. At the opposite end of the scale, with a quality measure of 0.0, is an omnidirectional soundfield. This is heard to be without direction or "in the head". As you'd expect, intermediate measures are heard as scaled between these two extremes.

And, from the footnotes describing what these measures are:

> [4] - _Incidence_ is measured in terms of the _(Active) Intensity_ vector.
> [5] - _Quality_ is measured as the magnitude of the _Energy Normalised (Active) Intensity_ vector, aka _rE_.
> [6] - _Gain_ reported is the _Potential-Kinetic Energy Mean_, aka _Soundfield Energy_.
> 

Pseudo-code to follow....

**Comment by joslloand** [comment] 2016-07-18 18:49
Calculating _gain_, in dB: _Potential-Kinetic Energy Mean_, aka _Soundfield Energy_

Given:
- (real) soundfield encoding coefficients*
- FuMa-MaxN encoding, [W, X, Y, Z]

*coefficients returned by planewave encoder

```
gain = 10 * log10( 0.5 * ((2*(W**2)) + X**2 + Y**2 + Z**2) )
```

**Comment by joslloand** [comment] 2016-07-18 19:12
_Energy Normalised (Active) Intensity_ vector, aka _rE_

Given:
- (real) soundfield encoding coefficients*
- FuMa-MaxN encoding, [W, X, Y, Z]

*coefficients returned by planewave encoder

```
active_energy_vector = (pow(2, 3./2)) * (W * [X, Y, Z]) / ((2*(W**2)) + X**2 + Y**2 + Z**2)
```
This pseudo-code returns a vector in cartesian coordinates. The magnitude of this vector is _quality_, aka _rE_ coefficient. Converting from cartesian to spherical coordinates is the way to return _r_ (_quality_), _theta_ (_azimuth_) and _phi_ (_elevation_) for a 3D plot.

**Comment by joslloand** [comment] 2016-07-18 19:29
And... finally, a follow-up note on how the previous plots / display are (or should have been!) generated.

_Potential Energy Normalised (Active) Intensity_ vector, aka  _(Active) Admittance_ vector, or _rV_

Given:
- (real) soundfield encoding coefficients*
- FuMa-MaxN encoding, [W, X, Y, Z]

*coefficients returned by planewave encoder

```
active_admittance_vector = (1 / pow(2, 1./2)) * [X, Y, Z] / W
```

This pseudo-code returns a vector in cartesian coordinates. The magnitude of this vector is _admittance_, aka _rV_ coefficient. Converting from cartesian to spherical coordinates is the way to return _r_ (_admittance_, _rV_), _theta_ (_azimuth_) and _phi_ (_elevation_) for a 3D plot.

## 

I'm thinking that we may want to include a switch in the display for users to select between _quality_ (_rE_) and _admittance_ (_rV_) display. Because soundfield _quality_ (_rE_) is closely associated with perception, this should be the default.

For new analysis tools coming to atk-sc3, we will (probably) be including an _admittance_ (_rV_) signal analyzer. Doing offers some useful analysis / synthesis networks to be designed. That _could_ be enough of a reason to include a switch in the atk-reaper GUIs to swap the view between _rE_ and _rV_.

ALSO... we'll want to bring the new signal analysis tools, for display(!), to atk-reaper. This could also imply we should include a switch in the atk-reaper GUIs to choose between _rE_ & _rV_.

**Comment by lossius** [comment] 2019-12-09 20:34
Closing this issue, as info is moved to Wiki. Not all of the discussion has been moved to the wiki, but it is pointing back here for further info, and that info remains accessible even if the issue is closed.

**Closed by lossius** 2019-12-09 20:34 UTC
Labels: enhancement

**Comment by joslloand** [comment] 2022-02-22 20:04
@lossius, yep... you're right, the admittance calc was missing a reciprocal. It should be:

`
active_admittance_vector = (1 / pow(2, 1./2)) * [X, Y, Z] / W
`

What we want is _velocity vector_ / _pressure_ OR the equivalent (_velocity vector_ * _pressure_) / _pressure squared_

**Comment by lossius** [comment] 2022-02-23 15:18
Tbnaks, @joslloand. Good to have that confirmed.
